### ISSUE TITLE
安装完成之后访问首页会出现 RuntimeException

### ISSUE THREAD

**Issue by upliu** [iiYii/getyii#130]
看错误是 assetsAutoCompress 这个组件在压缩的过程中抛出了异常。
RuntimeException
Unclosed string at position: 305386

vendor/tedivm/jshrink/src/JShrink/Minifier.php 第 476 行
throw new \RuntimeException('Unclosed string at position: ' . $startpos );

**Comment by forecho** [comment]
这个是因为 https://github.com/iiYii/getyii/commit/85248ff29a1b6fdffbcfe9e4db184c5185320343 功能导致的，你注释掉这行代码就 OK 了https://github.com/iiYii/getyii/blob/85248ff29a1b6fdffbcfe9e4db184c5185320343/common/config/main.php#L11

**Comment by upliu** [comment]
注释掉当然可以运行。但并没有解决问题啊，你那边能跑起来吗？看了下 www.getyii.com 也并没有进行合并。

**Comment by forecho** [comment]
这个扩展兼容性有点问题。我本地是正常的，服务器不能合并。

算了，已回滚代码了。
