### ISSUE TITLE
采用 basic 结构的模板，打包 vendor 发布，增加安装程序

### ISSUE THREAD

**Issue by upliu** [iiYii/getyii#145]
目前 getyii 使用 advanced 的模板，区分 backend frontend，需要为前后台指定不同域名，考虑到虚拟主机以及初级用户的使用习惯，如果能使用 basic 模板的代码结构，做到直接将所有代码上传到服务器web根目录就可以运行。针对此场景，后期可以考虑出打包的版本直接包含 vendor 目录，第一次打开站点出现安装提示，在浏览器界面直接安装。

**Comment by forecho** [comment]
据我所知，虚拟主机是不能配置入口文件的路径的吧？所以即使是 basic 虚拟主机也是没办法的吧？

在浏览器界面直接安装可以考虑支持。

**Comment by upliu** [comment]
虚拟主机一般有个 public_html ，默认访问到这里，类似于 yii2 的 web 目录，其他目录与  public_html 同级放置即可。

**Comment by forecho** [comment]
@upliu Yii2 是出于安全考虑才把入口文件放在 web 目录下的，当然你也可以把入口文档放在跟目录，但是这个不太安全，所以我不打算做这个。

当然你可以写一篇教程如何手动修改入口文件的，达到你想要的要求。
