### ISSUE TITLE
增加可选的富文本编辑器

### ISSUE THREAD

**Issue by upliu** [iiYii/getyii#146]
出了 coding 圈，学术圈，大部分人是不会使用 markdown 的，getyii 默认只有 markdown 编辑器，必然使得程序的用户面会比较窄。

**Comment by qiansen1386** [comment]
所以？用可视化的Markdown？

**Comment by upliu** [comment]
用可视化的所见即所得的富文本编辑器。

**Comment by forecho** [comment]
目前暂不打算支持富文本编辑器，但是我会抽时间换一个界面更加友好的 Markdown 编辑器。
