### ISSUE TITLE
composer install 卡主不动， 如下，就这个 一直不动

### ISSUE THREAD

**Issue by chenhui1221** [iiYii/getyii#149]
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 42 installs, 0 updates, 0 removals
  - Installing yiisoft/yii2 (dev-master 3dd586e):

**Comment by forecho** [comment]
一般这种情况都是因为 composer 被墙了，解决办法有两个：

1. 使用国内镜像：<https://pkg.phpcomposer.com/> 或者 <https://laravel-china.org/composer>
2. 自备梯子，科学上网

**Comment by chenhui1221** [comment]
@forecho   我用的就是国内镜像哦， 其他 插件是 可以安装的， 到 yii2  的时候就这样 卡着了。

**Comment by forecho** [comment]
https://pkg.phpcomposer.com/  有提到 "为什么基于 Yii2 创建的项目安装依赖包时即便设置了中国镜像依然很慢？"：

>yii2 通过 fxp/composer-asset-plugin 插件来安前端开发所用到依赖包，此插件会在安装完 php 依赖包之后再安装前端开发所依赖的 npm 或 bower 包， 所以导致再次前往 Github 下载资源，从而绕开了我们中国镜像。
参考：http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-from-composer
参考：https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/index.md
composer-asset-plugin 插件的用途是解决 php 项目中管理、安装 bower、 npm （nodejs包管理）包的，如果你采用的是 yii2 框架，请参考其文档。

你可以使用  `composer install -vvv` 命令安装就可以看到详细进度了。

**Comment by chenhui1221** [comment]
谢谢， 我看看
