### ISSUE TITLE
访问后台报错  symlink(): Cannot create symlink, error code(1314)

### ISSUE THREAD

**Issue by chenhui1221** [iiYii/getyii#150]
![image](https://user-images.githubusercontent.com/19380498/27119778-c2603ac8-5113-11e7-871d-f40c497b6dbe.png)

**Comment by forecho** [comment]
提示这个是因为你的环境是 Windows，不支持 symlink，把[这行](https://github.com/iiYii/getyii/blob/master/common/config/main.php#L34)配置去掉就可以了
