### ISSUE TITLE
composer install 出现问题

### ISSUE THREAD

**Issue by mingzhanliao** [iiYii/getyii#181]
E:\project_me\php\getyii>composer install

  [RuntimeException]
  require.bower-asset/PACE is invalid, it should not contain uppercase characters. Please use bower-asset/pace instead.

**Comment by mingzhanliao** [comment]
使用 composer2.0.7

**Comment by forecho** [comment]
@mingzhanliao https://github.com/iiYii/getyii/commit/5769c89a06d5b547911c1c947b7104ff8a4c60a3

**Comment by mingzhanliao** [comment]
Deprecation warning: require.bower-asset/At.js is invalid, it should not contain uppercase characters. Please use bower-asset/at.js instead. Make sure you fix this as Composer 2.0 will error.

似乎与composer2不兼容
以下为报错信息，使用composer1系列是可以的
E:\project_me\php\getyii>composer i
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires bower-asset/highlightjs, it could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Root composer.json requires bower-asset/pace, it could not be found in any version, there may be a typo in the package name.
  Problem 3
    - Root composer.json requires bower-asset/localforage, it could not be found in any version, there may be a typo in the package name.
  Problem 4
    - Root composer.json requires bower-asset/at.js, it could not be found in any version, there may be a typo in the package name.
  Problem 5
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> could not be found in any version, but the following packages provide it:
      - craftcms/cms Craft CMS
      - yidas/yii2-bower-asset Bower Assets for Yii 2 app provided via Composer repository
      - yidas/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - yidas/yii2-jquery jQuery Asset Bundle extension with fixed and CDN sources for Yii2 framework
      - jamband/yii2-ensure-unique-behavior This extension insert unique identifier automatically for the Yii 2 framework
      - taobig/php-helper A tool set for PHP projects
      - demokn/yii2-composer-asset
      - maiscrm/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - stiks/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - blackhive/yii2-app-advanced Yii 2 Advanced Project Template
      - cliff363825/yii2-bower-asset Yii2 bower asset
      - getdkan/recline recline.js module for DKAN/Drupal
      - kriss/yii2-advanced Yii2 advanced project template, Frontend for API and Backend with AdminLTE
      - maniakalen/tags Yii2 Element tags integration module
      - myzero1/yii2-app-advanced Yii 2 Advanced Project Template
      - onyijne/ovy Onsen-UI 2 + Vue.js 2 + Yii2 Basic Project Template
      - projectchina/yii2-app-advanced Yii 2 Advanced Project Template
      - success/yii2-app-api Yii2 Api Application Template
      - tanakahisateru/yii2-app-basic-npm How to use NPM with Yii 2 Basic Application Template
      - yuncms/framework The Yuncms Framework.
      Consider requiring one of these to satisfy the bower-asset/jquery requirement.
    - yiisoft/yii2[2.0.7, ..., 2.0.8] require bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> could not be found in any version, but the following packages provide it:
      - craftcms/cms Craft CMS
      - yidas/yii2-bower-asset Bower Assets for Yii 2 app provided via Composer repository
      - yidas/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - yidas/yii2-jquery jQuery Asset Bundle extension with fixed and CDN sources for Yii2 framework
      - jamband/yii2-ensure-unique-behavior This extension insert unique identifier automatically for the Yii 2 framework
      - taobig/php-helper A tool set for PHP projects
      - demokn/yii2-composer-asset
      - maiscrm/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - stiks/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - blackhive/yii2-app-advanced Yii 2 Advanced Project Template
      - cliff363825/yii2-bower-asset Yii2 bower asset
      - getdkan/recline recline.js module for DKAN/Drupal
      - kriss/yii2-advanced Yii2 advanced project template, Frontend for API and Backend with AdminLTE
      - maniakalen/tags Yii2 Element tags integration module
      - myzero1/yii2-app-advanced Yii 2 Advanced Project Template
      - onyijne/ovy Onsen-UI 2 + Vue.js 2 + Yii2 Basic Project Template
      - projectchina/yii2-app-advanced Yii 2 Advanced Project Template
      - success/yii2-app-api Yii2 Api Application Template
      - tanakahisateru/yii2-app-basic-npm How to use NPM with Yii 2 Basic Application Template
      - yuncms/framework The Yuncms Framework.
      Consider requiring one of these to satisfy the bower-asset/jquery requirement.
    - yiisoft/yii2[2.0.9, ..., 2.0.12.2] require bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> could not be found in any version, but the following packages provide it:
      - craftcms/cms Craft CMS
      - yidas/yii2-bower-asset Bower Assets for Yii 2 app provided via Composer repository
      - yidas/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - yidas/yii2-jquery jQuery Asset Bundle extension with fixed and CDN sources for Yii2 framework
      - jamband/yii2-ensure-unique-behavior This extension insert unique identifier automatically for the Yii 2 framework
      - taobig/php-helper A tool set for PHP projects
      - demokn/yii2-composer-asset
      - maiscrm/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - stiks/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - blackhive/yii2-app-advanced Yii 2 Advanced Project Template
      - cliff363825/yii2-bower-asset Yii2 bower asset
      - getdkan/recline recline.js module for DKAN/Drupal
      - kriss/yii2-advanced Yii2 advanced project template, Frontend for API and Backend with AdminLTE
      - maniakalen/tags Yii2 Element tags integration module
      - myzero1/yii2-app-advanced Yii 2 Advanced Project Template
      - onyijne/ovy Onsen-UI 2 + Vue.js 2 + Yii2 Basic Project Template
      - projectchina/yii2-app-advanced Yii 2 Advanced Project Template
      - success/yii2-app-api Yii2 Api Application Template
      - tanakahisateru/yii2-app-basic-npm How to use NPM with Yii 2 Basic Application Template
      - yuncms/framework The Yuncms Framework.
      Consider requiring one of these to satisfy the bower-asset/jquery requirement.
    - yiisoft/yii2[2.0.13, ..., 2.0.15.1] require bower-asset/jquery 3.2.*@stable | 3.1.*@stable | 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> could not be found in any version, but the following packages provide it:
      - craftcms/cms Craft CMS
      - yidas/yii2-bower-asset Bower Assets for Yii 2 app provided via Composer repository
      - yidas/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - yidas/yii2-jquery jQuery Asset Bundle extension with fixed and CDN sources for Yii2 framework
      - jamband/yii2-ensure-unique-behavior This extension insert unique identifier automatically for the Yii 2 framework
      - taobig/php-helper A tool set for PHP projects
      - demokn/yii2-composer-asset
      - maiscrm/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - stiks/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - blackhive/yii2-app-advanced Yii 2 Advanced Project Template
      - cliff363825/yii2-bower-asset Yii2 bower asset
      - getdkan/recline recline.js module for DKAN/Drupal
      - kriss/yii2-advanced Yii2 advanced project template, Frontend for API and Backend with AdminLTE
      - maniakalen/tags Yii2 Element tags integration module
      - myzero1/yii2-app-advanced Yii 2 Advanced Project Template
      - onyijne/ovy Onsen-UI 2 + Vue.js 2 + Yii2 Basic Project Template
      - projectchina/yii2-app-advanced Yii 2 Advanced Project Template
      - success/yii2-app-api Yii2 Api Application Template
      - tanakahisateru/yii2-app-basic-npm How to use NPM with Yii 2 Basic Application Template
      - yuncms/framework The Yuncms Framework.
      Consider requiring one of these to satisfy the bower-asset/jquery requirement.
    - yiisoft/yii2[2.0.16, ..., 2.0.18] require bower-asset/jquery 3.3.*@stable | 3.2.*@stable | 3.1.*@stable | 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> could not be found in any version, but the following packages provide it:
      - craftcms/cms Craft CMS
      - yidas/yii2-bower-asset Bower Assets for Yii 2 app provided via Composer repository
      - yidas/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - yidas/yii2-jquery jQuery Asset Bundle extension with fixed and CDN sources for Yii2 framework
      - jamband/yii2-ensure-unique-behavior This extension insert unique identifier automatically for the Yii 2 framework
      - taobig/php-helper A tool set for PHP projects
      - demokn/yii2-composer-asset
      - maiscrm/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - stiks/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - blackhive/yii2-app-advanced Yii 2 Advanced Project Template
      - cliff363825/yii2-bower-asset Yii2 bower asset
      - getdkan/recline recline.js module for DKAN/Drupal
      - kriss/yii2-advanced Yii2 advanced project template, Frontend for API and Backend with AdminLTE
      - maniakalen/tags Yii2 Element tags integration module
      - myzero1/yii2-app-advanced Yii 2 Advanced Project Template
      - onyijne/ovy Onsen-UI 2 + Vue.js 2 + Yii2 Basic Project Template
      - projectchina/yii2-app-advanced Yii 2 Advanced Project Template
      - success/yii2-app-api Yii2 Api Application Template
      - tanakahisateru/yii2-app-basic-npm How to use NPM with Yii 2 Basic Application Template
      - yuncms/framework The Yuncms Framework.
      Consider requiring one of these to satisfy the bower-asset/jquery requirement.
    - yiisoft/yii2[2.0.19, ..., 2.0.35] require bower-asset/jquery 3.4.*@stable | 3.3.*@stable | 3.2.*@stable | 3.1.*@stable | 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> could not be found in any version,
but the following packages provide it:
      - craftcms/cms Craft CMS
      - yidas/yii2-bower-asset Bower Assets for Yii 2 app provided via Composer repository
      - yidas/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - yidas/yii2-jquery jQuery Asset Bundle extension with fixed and CDN sources for Yii2 framework
      - jamband/yii2-ensure-unique-behavior This extension insert unique identifier automatically for the Yii 2 framework
      - taobig/php-helper A tool set for PHP projects
      - demokn/yii2-composer-asset
      - maiscrm/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - stiks/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - blackhive/yii2-app-advanced Yii 2 Advanced Project Template
      - cliff363825/yii2-bower-asset Yii2 bower asset
      - getdkan/recline recline.js module for DKAN/Drupal
      - kriss/yii2-advanced Yii2 advanced project template, Frontend for API and Backend with AdminLTE
      - maniakalen/tags Yii2 Element tags integration module
      - myzero1/yii2-app-advanced Yii 2 Advanced Project Template
      - onyijne/ovy Onsen-UI 2 + Vue.js 2 + Yii2 Basic Project Template
      - projectchina/yii2-app-advanced Yii 2 Advanced Project Template
      - success/yii2-app-api Yii2 Api Application Template
      - tanakahisateru/yii2-app-basic-npm How to use NPM with Yii 2 Basic Application Template
      - yuncms/framework The Yuncms Framework.
      Consider requiring one of these to satisfy the bower-asset/jquery requirement.
    - yiisoft/yii2[2.0.36, ..., 2.0.39.3] require bower-asset/jquery 3.5.*@stable | 3.4.*@stable | 3.3.*@stable | 3.2.*@stable | 3.1.*@stable | 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> could not be found in any version, but the following packages provide it:
      - craftcms/cms Craft CMS
      - yidas/yii2-bower-asset Bower Assets for Yii 2 app provided via Composer repository
      - yidas/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - yidas/yii2-jquery jQuery Asset Bundle extension with fixed and CDN sources for Yii2 framework
      - jamband/yii2-ensure-unique-behavior This extension insert unique identifier automatically for the Yii 2 framework
      - taobig/php-helper A tool set for PHP projects
      - demokn/yii2-composer-asset
      - maiscrm/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - stiks/yii2-composer-bower-skip A Composer package that allows you to install or update Yii2 without Bower-Asset
      - blackhive/yii2-app-advanced Yii 2 Advanced Project Template
      - cliff363825/yii2-bower-asset Yii2 bower asset
      - getdkan/recline recline.js module for DKAN/Drupal
      - kriss/yii2-advanced Yii2 advanced project template, Frontend for API and Backend with AdminLTE
      - maniakalen/tags Yii2 Element tags integration module
      - myzero1/yii2-app-advanced Yii 2 Advanced Project Template
      - onyijne/ovy Onsen-UI 2 + Vue.js 2 + Yii2 Basic Project Template
      - projectchina/yii2-app-advanced Yii 2 Advanced Project Template
      - success/yii2-app-api Yii2 Api Application Template
      - tanakahisateru/yii2-app-basic-npm How to use NPM with Yii 2 Basic Application Template
      - yuncms/framework The Yuncms Framework.
      Consider requiring one of these to satisfy the bower-asset/jquery requirement.
    - Root composer.json requires yiisoft/yii2 >=2.0.6 -> satisfiable by yiisoft/yii2[2.0.6, ..., 2.0.39.3].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by forecho** [comment]
是的，由于项目有点历史了，推荐使用 composer 1

**Comment by mingzhanliao** [comment]
好的
