### ISSUE TITLE
[question]自己访问自己的主页是否可以不增加访问次数

### ISSUE THREAD

**Issue by lichunqiang** [iiYii/getyii#41]
衍生出来，如果未登录状态访问主页 是否限定 不增加访问量

**Comment by lichunqiang** [comment]
不知道这块的设计是怎样 - -！

**Comment by forecho** [comment]
目前只是简单粗暴的刷新一下就增加一次访问次数。
你说的可以有：
- 游客不增长访问次数
- 自身不增长访问次数

**Comment by forecho** [comment]
@lichunqiang 欢迎发 PR
