### ISSUE TITLE
[TBD] xss

### ISSUE THREAD

**Issue by lichunqiang** [iiYii/getyii#47]
### PHP

https://github.com/yiisoft/yii2/blob/master/docs/guide/security-best-practices.md#avoiding-xss

使用 `\yii\helpers\HtmlPurifier`

### 前端预览

https://github.com/lichunqiang/getyii/commit/de75322363470f9d6bd7c5637f00c11b44a62488

**Comment by forecho** [comment]
RP 呢？

**Comment by lichunqiang** [comment]
js  已经改了，主要是考虑php的处理

> Note that HtmlPurifier processing is quite heavy so consider adding caching.

**Comment by lichunqiang** [comment]
https://github.com/cebe/markdown/issues/106
cebe 说也要用 HtmlPurifier
